#!/usr/bin/env python
"""Download all possible remote data to make sure remote data is available."""

import os
import tempfile
import subprocess

import sncosmo

with tempfile.TemporaryDirectory() as dirname:
    os.environ['SNCOSMO_DATA_DIR'] = dirname
    print("set SNCOSMO_DATA_DIR to", dirname)

    # Bandpasses
    for name, _ in sncosmo.builtins._BANDPASSES._loaders.keys():
        band = sncosmo.get_bandpass(name)
    for name, _ in sncosmo.builtins._BANDPASS_INTERPOLATORS._loaders.keys():
        band = sncosmo.get_bandpass(name, 0.0)

    # Sources
    for name, version in sncosmo.builtins._SOURCES._loaders.keys():
        source = sncosmo.get_source(name, version=version)

    # Magsystems
    for name, _ in sncosmo.builtins._MAGSYSTEMS._loaders.keys():
        ms = sncosmo.get_magsystem(name)

    print("downloaded everything successfully.")
